### ISSUE TITLE
[Suggestion] Support for EU power system

### ISSUE THREAD

**Issue by drenough** [ZeroNoRyouki/ExtremeReactors2#103]
Hi, sorry to bother you here, just wanted to ask if you could add support for IC2 Classic energy system EU for 1.19.2 please ? In IC2 Classic, they have Flux Generator which convert EU power to FE and others but there's no way to use energy from reactor for IC2 machines which are EU and not FE :(.

**Comment by ZeroNoRyouki** [comment]
If the IC2 Classic guys are OK with it I will look into it. Would you ask them on their repository or CF mod page?

**Comment by drenough** [comment]
I opened issue on their page here: https://github.com/TinyModularThings/IC2Classic/issues/499

**Comment by Speiger** [comment]
Ok, i don't want to sound like bad talking this mod.
But IC2C had 1.7.10 RF/FE => EU converters, but after knowing how brokenly balanced this mod is in terms of how badly they would break EU balance I removed them in future versions.

While I can't say "You are not allowed to use EU API" since that would be against your rights.
I would kindly ask you, if you add EU support that you implement EU specific balancing and nerf the mod drastically in terms of how much they produce. But only in EU production.

Otherwise I kindly ask, please don't support EU. While EU also has its own power creep, I re-balanced a lot so that every power generation is viable in some form and none outshines the other to badly.

This one would most likely would outshine everything, with the current balancing..

To give a example. With the current balancing a Nuclear reactor, with "Nether Star" fuel and the best cooling can produce at most 4-6kish EU/t but that is with the worst efficiency, because the higher the efficiency the lower your max output gets.

So your average player will get 2-3k/EU production with the most efficient setups.

In General if you add EU support, please account for EU Balancing (do own tests) and make it another viable option, but not outshining.

**Comment by ZeroNoRyouki** [comment]
That's why I've asked to ask you guys.

**Comment by Speiger** [comment]
And I thank you for that ^^

**Comment by ZeroNoRyouki** [comment]
You are welcome!
You should also take ER 1.16+ for a spin since it is not as much op as it was in 1.12 ;)
