### ISSUE TITLE
Reactor not outputting power. ATM9, ZeroCore 2.1.40, Extreme Reactors 2.0.76.

### ISSUE THREAD

**Issue by Sakurax64** [ZeroNoRyouki/ExtremeReactors2#135]
As of now there seems to be no way of getting power out of a reactor using power taps.
We tried Energy Cables from Powah, Energy Pipes from Pipez, Universal Cables from Mekanism and Energy Conduits from EnderIO.
Directly connecting storage devices to the tap does not work either. Logs do not show anything.
Running version 2.0.24 of ATM9, ZeroCore 2.1.40 and Extreme Reactors 2.0.76.

**Comment by ZeroNoRyouki** [comment]
Which type of taps are you using ?

Passive taps need to be extracted from. Active taps automatically output energy and block extraction attempts

**Comment by ZeroNoRyouki** [comment]
I did a quick test:
- direct connection to an active power tap : it works
- active power tap with all the cables you mentioned : they works
- passive power tap: all cables you mentioned, set in auto-extract mode works, with the exception of the powah one because I can't figure out how to make it auto-extract (if they can)


![image](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/b79dd3e8-d41a-4692-b125-6ecf003c6084)

**Comment by Sakurax64** [comment]
> Which type of taps are you using ?
> 
> Passive taps need to be extracted from. Active taps automatically output energy and block extraction attempts

I was using the passive tap and not manually extracting, thanks. Another RTFM for me!

**Comment by ZeroNoRyouki** [comment]
You are welcome
