### ISSUE TITLE
Fluidizer Uranium Recipe Not Working

### ISSUE THREAD

**Issue by MadSciSlack** [ZeroNoRyouki/ExtremeReactors2#147]
There's a Fluidizer recipe that turns Mekanism's Uranium Ingots into the fluid version of Yellorium.  For some reason, this isn't working.  The Uranium goes into the Fluidizer, but nothing happens.  The Fluidizer is full on Uranium Ingots and FE.

Can please I get some insight on why this isn't working?

![2024-03-20_15 25 14](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/79179402/ccb33d7a-ebd3-4fee-8255-704f26de7ea4)
![2024-03-20_15 34 30](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/79179402/7f0ee5bd-3794-4b3b-bf29-fd6a43afc9eb)

**Comment by MadSciSlack** [comment]
Update: It's not just the Uranium Ingots that won't work.  The Fluidizer seems to do this with ALL reactant type ingots.  I've tried Cyanite and Magentite, and nothing seems to convert.

**Comment by MadSciSlack** [comment]
Further update: It's apparently because I had 2 solid injector ports.  This mod is good, but the lack of information is frustrating.

The in-game book could be a lot clearer about a few things:

- A reactor using Reinforced tier parts must contain ONLY Reinforced tier parts.
- The Fluidizer must only have 1 solid injection port to perform solid to fluid conversions.
- Mention cross-compatible fuels from other mods.

There are some spelling and grammar errors.  If you need help with English, just let me know and I will help.  I am a capable editor and am happy to offer this service for your mod if you are interested.

**Comment by MadSciSlack** [comment]
Feel free to close this issue once you've seen these comments.

**Comment by ZeroNoRyouki** [comment]
Thank you for your comments.

Do you really think that I need to spell out that you can't mix parts from different variants? Isn't it obvious since you basically have the same parts in each variant?

The page about the Fluidizer operation mode already mention which injectors and how many of them you need for each mode/recipe type

The problem with mentioning fuels from other mods is that I don't know what fuels are available in every mod pack and the book is basically a static text. The book so tells you how you can find then in your inventories (you can even search for them in JEI if you enable the tooltip search feature in the config files of JEI)

Are there any other info missing from the book?

Thank you
Z
