### ISSUE TITLE
The Extrem Book has some Issues

### ISSUE THREAD

**Issue by jajajafeti** [ZeroNoRyouki/ExtremeReactors2#40]
Hello, I just downloaded ExtremeReactors2-1.16.4-2.0.23 and got Patchouli-1.16.4-50 installed. Now the recipies and basicaly the Items when u hover over them in the book, wont show anything or sometimes the wrong thing.

In this example it shows the recipie from the bottom
![image](https://user-images.githubusercontent.com/61298096/111829128-93e74a00-88ec-11eb-8060-cd43568dcf63.png)
anotherone
![image](https://user-images.githubusercontent.com/61298096/111829630-38698c00-88ed-11eb-9840-bbfe99fbcaaf.png)

Maybe u want to look 4 ur selfe trough the book. I cant see how this is an issue on the user side.
Let me know if u need morte info.

**Comment by KuwuroUsagi** [comment]
Many of the recipes shown in the book indeed do not match names/images, also some do not have names when hovered at all

**Comment by macks2008** [comment]
I'm also experiencing this issue on Minecraft 1.18.2
![image](https://user-images.githubusercontent.com/7110033/208305416-1d393ec0-2aa0-4bb5-94eb-92e5df74426e.png)
# versions 
(based on the mod menu, though the mod file names seems to corroborate):
ExtremeReactors2: 1.18.2-2.0.51
Patchouli: 1.18.2-71.1
forge: 40.1.84

**Comment by ZeroNoRyouki** [comment]
Recipes and icons are OK, it's the displayed toolip that's wrong (it use the the one from the bottom recipe). Unfortunately this is a problem in Patchouli itself, because it does not take in consideration that one of its recipe page can be used in a double template like I'm doing in the ER book. I've had to put code in to actually stop Patchouli drawing both recipes on top of each other but I can't do the same for the tooltip

**Comment by macks2008** [comment]
If I were you I would take a look at PneumaticCraft Repressurized's code for this. They also have pages containing multiple recipes, but the tooltips rendered correctly.
![image](https://user-images.githubusercontent.com/7110033/210143885-1d4dbd1b-6dcc-4287-8539-35552f9042ec.png)

**Comment by ZeroNoRyouki** [comment]
They are using the default crafting page which pose a bit of a problem:

![image](https://user-images.githubusercontent.com/7107662/210177223-601da72f-8274-4e94-90f6-023a40207340.png)

**Comment by ZeroNoRyouki** [comment]
Found a way around both problems:

![image](https://user-images.githubusercontent.com/7107662/210603652-e17b8e09-09a6-4a18-abe2-45dc7f9b5edf.png)

**Comment by macks2008** [comment]
ah, I see what you mean. You had to shorten the block names... maybe that should tell you something about your block names LOL? like couldn't you call it Reactor FE Tap?
anyway, glad it's straightened out. So wait, what did you end up doing?

**Comment by ZeroNoRyouki** [comment]
Nah, I didn't changes the block names. I reworked how the crafting page of Patchouli handle the titles so that I could use custom ones instead of the block names.

**Comment by macks2008** [comment]
That's what I mean. You needed to customize the page so that you could use titles that aren't ungodly long like... Well, your block names which have ungodly long names. 
(Sure, Reactor Passive Forge Energy Power Tap is *descriptive*, but did it ever occur to you you might be better off merging all of these blocks into one block somehow, since they all have a single responsibility "get energy out of the machine"? Of course, I'm making the assumption that's actually possible in this instance, but I feel like there must be some sort of way to leverage Java's polymorphism faculties here)

**Comment by ZeroNoRyouki** [comment]
They are split by design. A Reactor support only one output power system (if you want two different energy types you need two reactors) as I don't want you guys to build a fit-for-all reactor.

The passive / active split is to avoid having a GUI for setting that operation mode, as it will be more difficult for the player to troubleshoot: now you see directly that you are connecting a passive cable to a passive port.

That's why there are N power taps blocks.

Z

PS: they are already implemented by a single class plus one per the power system adapter
