### ISSUE TITLE
Feature request: Be able to change output/input on fluid ports while multiblock is broken

### ISSUE THREAD

**Issue by kirayatail** [ZeroNoRyouki/ExtremeReactors2#51]
Hey! Thanks for doing some really nice work.

I would like to see the possibility to change input/output direction on fluid ports (both on reactor and turbine) while the multiblock is still being built. The way it worked in ExtremeReactors 1 with a wrench seems fine to me, but I'm open to other interactions. The reversed color coding seen in v1 was also helpful to match up the ports. I was stuck for a long time trying different combinations of active/passive ports and finally I jumped inside the running turbine to solve the problem I usually build reactors and turbines directly attached, so there's no way to right-click the ports while they are fully built.

Using version 2.0.23

**Comment by ZeroNoRyouki** [comment]
The funny thing is, you can already do it. 

If you use a wrench on a fluid or access port, it will toggle it from input to output (or viceversa). You will not see it until the multiblock is formed (because, let's say, all the blocks in a "broken" multiblock use their default model/textures)

I've changed the model used for i/o ports in "broken" multiblocks to reflect their direction in the upcoming release
