### ISSUE TITLE
Energy disappears

### ISSUE THREAD

**Issue by ThisIsDevolper** [ZeroNoRyouki/ExtremeReactors2#95]
Playing with boosted reactors (with x10 production multiplayer) i was able to produce 20 Mrf/t, but the max output is 10 Mrf/t, because of probably the dimensions of the internal battery, and the remaining 10 Mrf/t just disappears. I think that a simple solution could be increasing the capacity of the internal battery or making it configurable

**Comment by ZeroNoRyouki** [comment]
The internal buffer size is fixed in <1.16 and a function of the Reactor size on 1.16+, and the size is part of the mod balancing strategy.

Any energy produced that does not fit inside the buffer is lost, as clearly stated by the mod and its manual.

So, all is working as designed. 

And any external modification on the energy production rate is not supported. If you need more energy per tick you can changed the production multiplier in the config file.

**Comment by ThisIsDevolper** [comment]
in fact the production multiplier is changed in the config files, but with the fact that the production of the reactor (normally) would be of 2 Mrf/t with the multiplier of x10 it becomes more than 10Mrf/t and the port doesn't output more than that, so 10Mrf/t disappear. I'm not asking to change all the mod to solve this problem, i'm only thinking of find a solution

**Comment by ZeroNoRyouki** [comment]
What you can do, if you are on 1.12 as I belive, is getting the energy out of the Reactor as fast as you can. The Power Tap limit is the internal buffer size per tick

Or build 2 reactors with half the multiplier

**Comment by ThisIsDevolper** [comment]
in reality for me it isn't a problem (i changed the config to make sure that the max production that a reactor can reach is exactly the limit of the export) but if the internal buffer was configurable this wasn't a problem... so if in the newer versions you can add a multiplier for the buffer that should fix the problem...
